// academia.js - Exercícios de Academia (100+ exercícios)
import { TIPOS_EXERCICIO, GRUPOS_MUSCULARES, EQUIPAMENTOS, IMPACTO } from './classificacao.js';

export const EXERCICIOS_ACADEMIA = {
  // ==========================================
  // PEITO (12 variações)
  // ==========================================
  peito: [
    {
      id: 'supino_reto',
      name: 'Supino Reto',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['peito', 'triceps', 'ombro_frontal'],
      equipment: ['barra_olimpica', 'banco'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['supino_inclinado', 'supino_declinado', 'supino_halteres'],
    },
    {
      id: 'supino_inclinado',
      name: 'Supino Inclinado',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['peito_superior', 'ombro_frontal', 'triceps'],
      equipment: ['barra_olimpica', 'banco'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['supino_reto', 'supino_inclinado_halteres', 'crucifixo_inclinado'],
    },
    {
      id: 'supino_declinado',
      name: 'Supino Declinado',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['peito'],
      equipment: ['barra_olimpica', 'banco'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['supino_reto', 'flexao_declinada'],
    },
    {
      id: 'supino_halteres',
      name: 'Supino com Halteres',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['peito', 'triceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['supino_reto', 'supino_inclinado_halteres'],
    },
    {
      id: 'crucifixo',
      name: 'Crucifixo Reto',
      emoji: '🦅',
      type: 'forca',
      muscle: ['peito'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['crucifixo_inclinado', 'peck_deck'],
    },
    {
      id: 'crucifixo_inclinado',
      name: 'Crucifixo Inclinado',
      emoji: '🦅',
      type: 'forca',
      muscle: ['peito_superior'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['crucifixo', 'supino_inclinado'],
    },
    {
      id: 'cross_over',
      name: 'Cross Over',
      emoji: '❌',
      type: 'forca',
      muscle: ['peito'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['crucifixo', 'peck_deck'],
    },
    {
      id: 'peck_deck',
      name: 'Peck Deck',
      emoji: '🦾',
      type: 'forca',
      muscle: ['peito'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['crucifixo', 'cross_over'],
    },
    {
      id: 'flexao_com_peso',
      name: 'Flexão com Peso nas Costas',
      emoji: '💪',
      type: 'forca',
      muscle: ['peito', 'triceps'],
      equipment: ['halteres'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['flexao_tradicional', 'supino_reto'],
    },
    {
      id: 'supino_reto_maquina',
      name: 'Supino Reto Máquina',
      emoji: '🏗️',
      type: 'forca',
      muscle: ['peito', 'triceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['supino_reto', 'supino_inclinado_maquina'],
    },
    {
      id: 'pullover',
      name: 'Pullover com Halteres',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['peito', 'costas'],
      equipment: ['halteres', 'banco'],
      difficulty: 3,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['pullover_polia', 'supino_reto'],
    },
    {
      id: 'dips_banco',
      name: 'Dips no Banco',
      emoji: '💪',
      type: 'forca',
      muscle: ['triceps', 'peito'],
      equipment: ['banco'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['paralelas', 'triceps_banco'],
    },
  ],

  // ==========================================
  // COSTAS (14 variações)
  // ==========================================
  costas: [
    {
      id: 'puxada_frontal',
      name: 'Puxada Frontal',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 4,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['puxada_aberta', 'puxada_inversa', 'barra_fixa'],
    },
    {
      id: 'puxada_aberta',
      name: 'Puxada Aberta',
      emoji: '🦅',
      type: 'forca',
      muscle: ['costas', 'ombro'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['puxada_frontal', 'barra_pegada_aberta'],
    },
    {
      id: 'puxada_inversa',
      name: 'Puxada Inversa',
      emoji: '🔄',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['puxada_frontal', 'remada_baixa'],
    },
    {
      id: 'remada_baixa',
      name: 'Remada Baixa',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 4,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['remada_curvada', 'remada_unilateral'],
    },
    {
      id: 'remada_curvada',
      name: 'Remada Curvada',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps', 'lombar'],
      equipment: ['barra_olimpica'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['remada_baixa', 'remada_unilateral', 'levantamento_terra'],
    },
    {
      id: 'remada_unilateral',
      name: 'Remada Unilateral (Serrote)',
      emoji: '🪚',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['remada_curvada', 'remada_baixa'],
    },
    {
      id: 'remada_cavalinho',
      name: 'Remada Cavalinho',
      emoji: '🐴',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['remada_unilateral', 'remada_curvada'],
    },
    {
      id: 'puxada_polia_alta',
      name: 'Puxada na Polia Alta',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'ombro'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['puxada_frontal', 'cross_over_inverso'],
    },
    {
      id: 'levantamento_terra',
      name: 'Levantamento Terra',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'lombar', 'gluteo', 'posterior'],
      equipment: ['barra_olimpica'],
      difficulty: 4,
      caloriesPerMin: 12,
      baseSets: 3,
      baseReps: 6,
      impacto: 'alto',
      tempoMedio: 45,
      variations: ['stiff', 'sumo_terra'],
    },
    {
      id: 'stiff',
      name: 'Stiff',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['posterior', 'lombar', 'gluteo'],
      equipment: ['barra_olimpica'],
      difficulty: 3,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['levantamento_terra', 'mesa_flexora'],
    },
    {
      id: 'barra_fixa_academia',
      name: 'Barra Fixa',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['barra'],
      difficulty: 4,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 6,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['puxada_frontal', 'barra_pegada_aberta'],
    },
    {
      id: 't_bar',
      name: 'T-Bar Row',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['barra_olimpica'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['remada_curvada', 'remada_baixa'],
    },
    {
      id: 'pullover_polia',
      name: 'Pullover na Polia',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'peito'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['pullover', 'puxada_frontal'],
    },
    {
      id: 'hiperextensao',
      name: 'Hiperextensão Lombar',
      emoji: '🔙',
      type: 'forca',
      muscle: ['lombar', 'gluteo'],
      equipment: ['banco'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['superman', 'levantamento_terra'],
    },
  ],

  // ==========================================
  // OMBRO (10 variações)
  // ==========================================
  ombro: [
    {
      id: 'desenvolvimento',
      name: 'Desenvolvimento (Shoulder Press)',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['ombro', 'triceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['desenvolvimento_arnold', 'desenvolvimento_barra', 'elevacao_lateral'],
    },
    {
      id: 'desenvolvimento_arnold',
      name: 'Arnold Press',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['ombro', 'ombro_frontal'],
      equipment: ['halteres', 'banco'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['desenvolvimento', 'elevacao_frontal'],
    },
    {
      id: 'elevacao_lateral',
      name: 'Elevação Lateral',
      emoji: '🕊️',
      type: 'forca',
      muscle: ['ombro_lateral'],
      equipment: ['halteres'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 4,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['elevacao_frontal', 'crucifixo_inverso'],
    },
    {
      id: 'elevacao_frontal',
      name: 'Elevação Frontal',
      emoji: '🦾',
      type: 'forca',
      muscle: ['ombro_frontal'],
      equipment: ['halteres'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['elevacao_lateral', 'desenvolvimento'],
    },
    {
      id: 'crucifixo_inverso',
      name: 'Crucifixo Inverso (Posterior)',
      emoji: '🔄',
      type: 'forca',
      muscle: ['ombro', 'costas'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['elevacao_lateral', 'remada_curvada'],
    },
    {
      id: 'encolhimento',
      name: 'Encolhimento (Trapézio)',
      emoji: '🤷',
      type: 'forca',
      muscle: ['ombro'],
      equipment: ['halteres'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['encolhimento_barra', 'remada_curvada'],
    },
    {
      id: 'face_pull',
      name: 'Face Pull',
      emoji: '🧵',
      type: 'forca',
      muscle: ['ombro', 'costas'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['crucifixo_inverso', 'remada_baixa'],
    },
    {
      id: 'elevacao_lateral_polia',
      name: 'Elevação Lateral na Polia',
      emoji: '🕊️',
      type: 'forca',
      muscle: ['ombro_lateral'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['elevacao_lateral', 'face_pull'],
    },
    {
      id: 'desenvolvimento_maquina',
      name: 'Desenvolvimento Máquina',
      emoji: '🏗️',
      type: 'forca',
      muscle: ['ombro'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['desenvolvimento', 'desenvolvimento_arnold'],
    },
    {
      id: 'rotacao_manguito',
      name: 'Rotação de Manguito',
      emoji: '🔧',
      type: 'mobilidade',
      muscle: ['ombro'],
      equipment: ['halteres', 'banco'],
      difficulty: 1,
      caloriesPerMin: 3,
      baseSets: 2,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['alongamento_ombro', 'elevacao_lateral'],
    },
  ],

  // ==========================================
  // BÍCEPS (8 variações)
  // ==========================================
  biceps: [
    {
      id: 'rosca_direta',
      name: 'Rosca Direta',
      emoji: '💪',
      type: 'forca',
      muscle: ['biceps'],
      equipment: ['barra_olimpica'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['rosca_alternada', 'rosca_martelo', 'rosca_scott'],
    },
    {
      id: 'rosca_alternada',
      name: 'Rosca Alternada',
      emoji: '💪',
      type: 'forca',
      muscle: ['biceps'],
      equipment: ['halteres'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['rosca_direta', 'rosca_martelo'],
    },
    {
      id: 'rosca_martelo',
      name: 'Rosca Martelo',
      emoji: '🔨',
      type: 'forca',
      muscle: ['biceps', 'antebraco'],
      equipment: ['halteres'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['rosca_alternada', 'rosca_inversa'],
    },
    {
      id: 'rosca_scott',
      name: 'Rosca Scott',
      emoji: '💪',
      type: 'forca',
      muscle: ['biceps'],
      equipment: ['barra_olimpica', 'banco'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['rosca_direta', 'rosca_concentrada'],
    },
    {
      id: 'rosca_concentrada',
      name: 'Rosca Concentrada',
      emoji: '🎯',
      type: 'forca',
      muscle: ['biceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['rosca_scott', 'rosca_alternada'],
    },
    {
      id: 'rosca_inversa',
      name: 'Rosca Inversa',
      emoji: '🔄',
      type: 'forca',
      muscle: ['antebraco', 'biceps'],
      equipment: ['barra_olimpica'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['rosca_martelo', 'rosca_punho'],
    },
    {
      id: 'rosca_polia',
      name: 'Rosca na Polia',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['biceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['rosca_direta', 'rosca_concentrada'],
    },
    {
      id: 'rosca_21',
      name: 'Rosca 21',
      emoji: '💪',
      type: 'forca',
      muscle: ['biceps'],
      equipment: ['barra_olimpica'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 21,
      impacto: 'baixo',
      tempoMedio: 40,
      variations: ['rosca_direta', 'rosca_scott'],
    },
  ],

  // ==========================================
  // TRÍCEPS (8 variações)
  // ==========================================
  triceps: [
    {
      id: 'triceps_corda',
      name: 'Tríceps Corda',
      emoji: '🪢',
      type: 'forca',
      muscle: ['triceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['triceps_pulley', 'triceps_frances'],
    },
    {
      id: 'triceps_pulley',
      name: 'Tríceps Pulley',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['triceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['triceps_corda', 'triceps_testa'],
    },
    {
      id: 'triceps_testa',
      name: 'Tríceps Testa',
      emoji: '🤕',
      type: 'forca',
      muscle: ['triceps'],
      equipment: ['barra_olimpica', 'banco'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['triceps_frances', 'triceps_pulley'],
    },
    {
      id: 'triceps_frances',
      name: 'Tríceps Francês',
      emoji: '🥖',
      type: 'forca',
      muscle: ['triceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['triceps_testa', 'triceps_corda'],
    },
    {
      id: 'triceps_banco',
      name: 'Tríceps Banco (Dips)',
      emoji: '💪',
      type: 'forca',
      muscle: ['triceps', 'peito'],
      equipment: ['banco'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['paralelas', 'dips_banco'],
    },
    {
      id: 'triceps_coice',
      name: 'Tríceps Coice',
      emoji: '🦵',
      type: 'forca',
      muscle: ['triceps'],
      equipment: ['halteres', 'banco'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['triceps_frances', 'triceps_pulley'],
    },
    {
      id: 'triceps_supinado',
      name: 'Tríceps Supinado',
      emoji: '🔄',
      type: 'forca',
      muscle: ['triceps'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['triceps_corda', 'triceps_pulley'],
    },
    {
      id: 'fundo_paralelas',
      name: 'Fundo em Paralelas',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['triceps', 'peito'],
      equipment: ['barra'],
      difficulty: 4,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['paralelas', 'triceps_banco'],
    },
  ],

  // ==========================================
  // PERNAS (20 variações)
  // ==========================================
  pernas: [
    {
      id: 'leg_press',
      name: 'Leg Press',
      emoji: '🦵',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 8,
      baseSets: 4,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['leg_press_unilateral', 'hack', 'agachamento_livre'],
    },
    {
      id: 'leg_press_unilateral',
      name: 'Leg Press Unilateral',
      emoji: '🦵',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['maquina'],
      difficulty: 3,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['leg_press', 'agachamento_unilateral'],
    },
    {
      id: 'cadeira_extensora',
      name: 'Cadeira Extensora',
      emoji: '🪑',
      type: 'forca',
      muscle: ['quadriceps'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 4,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['leg_press', 'agachamento_livre'],
    },
    {
      id: 'mesa_flexora',
      name: 'Mesa Flexora',
      emoji: '🦵',
      type: 'forca',
      muscle: ['posterior'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 4,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['stiff', 'cadeira_flexora'],
    },
    {
      id: 'cadeira_flexora',
      name: 'Cadeira Flexora',
      emoji: '🪑',
      type: 'forca',
      muscle: ['posterior'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['mesa_flexora', 'stiff'],
    },
    {
      id: 'hack',
      name: 'Hack Machine',
      emoji: '🏗️',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['maquina'],
      difficulty: 3,
      caloriesPerMin: 9,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['leg_press', 'agachamento_livre'],
    },
    {
      id: 'agachamento_barra',
      name: 'Agachamento com Barra',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo', 'lombar'],
      equipment: ['barra_olimpica'],
      difficulty: 4,
      caloriesPerMin: 12,
      baseSets: 4,
      baseReps: 8,
      impacto: 'alto',
      tempoMedio: 45,
      variations: ['agachamento_frontal', 'leg_press', 'hack'],
    },
    {
      id: 'agachamento_frontal',
      name: 'Agachamento Frontal',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['quadriceps', 'core'],
      equipment: ['barra_olimpica'],
      difficulty: 4,
      caloriesPerMin: 11,
      baseSets: 4,
      baseReps: 8,
      impacto: 'alto',
      tempoMedio: 45,
      variations: ['agachamento_barra', 'hack'],
    },
    {
      id: 'stiff_barra',
      name: 'Stiff com Barra',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['posterior', 'lombar', 'gluteo'],
      equipment: ['barra_olimpica'],
      difficulty: 3,
      caloriesPerMin: 9,
      baseSets: 4,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['mesa_flexora', 'levantamento_terra'],
    },
    {
      id: 'panturrilha_sentado',
      name: 'Panturrilha Sentado',
      emoji: '🦶',
      type: 'forca',
      muscle: ['panturrilha'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 4,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['panturrilha_em_pe', 'panturrilha_unilateral'],
    },
    {
      id: 'panturrilha_em_pe',
      name: 'Panturrilha em Pé',
      emoji: '🦶',
      type: 'forca',
      muscle: ['panturrilha'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 4,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['panturrilha_sentado', 'panturrilha_unilateral'],
    },
    {
      id: 'abdutora',
      name: 'Abdutora',
      emoji: '🦵',
      type: 'forca',
      muscle: ['abdutor', 'gluteo'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['adutora', 'afundo_lateral'],
    },
    {
      id: 'adutora',
      name: 'Adutora',
      emoji: '🦵',
      type: 'forca',
      muscle: ['adutor'],
      equipment: ['maquina'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['abdutora', 'agachamento_sumo'],
    },
    {
      id: 'gluteo_polia',
      name: 'Glúteo na Polia',
      emoji: '🍑',
      type: 'forca',
      muscle: ['gluteo'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['ponte_gluteo', 'elevacao_quadril'],
    },
    {
      id: 'gluteo_4_apoios',
      name: 'Glúteo 4 Apoios',
      emoji: '🍑',
      type: 'forca',
      muscle: ['gluteo'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['ponte_gluteo', 'gluteo_polia'],
    },
    {
      id: 'elevacao_pelvica',
      name: 'Elevação Pélvica (Hip Thrust)',
      emoji: '🍑',
      type: 'forca',
      muscle: ['gluteo'],
      equipment: ['banco', 'halteres'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 4,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 40,
      variations: ['ponte_gluteo', 'gluteo_4_apoios'],
    },
    {
      id: 'bom_dia',
      name: 'Good Morning',
      emoji: '☀️',
      type: 'forca',
      muscle: ['posterior', 'lombar', 'gluteo'],
      equipment: ['barra_olimpica'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['stiff', 'hiperextensao'],
    },
    {
      id: 'afundo_halteres',
      name: 'Afundo com Halteres',
      emoji: '🚶',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['halteres'],
      difficulty: 3,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['afundo', 'passada_andando'],
    },
    {
      id: 'bulgaro',
      name: 'Agachamento Búlgaro',
      emoji: '🇧🇬',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['banco'],
      difficulty: 4,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['afundo_halteres', 'agachamento_unilateral'],
    },
    {
      id: 'sumo_terra',
      name: 'Sumô Terra',
      emoji: '🤼',
      type: 'forca',
      muscle: ['adutor', 'gluteo', 'posterior'],
      equipment: ['barra_olimpica'],
      difficulty: 4,
      caloriesPerMin: 11,
      baseSets: 3,
      baseReps: 6,
      impacto: 'alto',
      tempoMedio: 45,
      variations: ['levantamento_terra', 'agachamento_sumo'],
    },
  ],

  // ==========================================
  // ABDÔMEN (8 variações)
  // ==========================================
  abdomen: [
    {
      id: 'crunch_maquina',
      name: 'Crunch na Máquina',
      emoji: '🏗️',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 4,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['abdominal_tradicional', 'crunch_cabo'],
    },
    {
      id: 'crunch_cabo',
      name: 'Crunch no Cabo',
      emoji: '🧵',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['maquina'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['crunch_maquina', 'abdominal_tradicional'],
    },
    {
      id: 'elevacao_pernas_barra',
      name: 'Elevação de Pernas na Barra',
      emoji: '🦵',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['barra'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['hanging_leg_raise', 'elevacao_joelhos'],
    },
    {
      id: 'ab_wheel',
      name: 'Ab Wheel (Roda Abdominal)',
      emoji: '🛞',
      type: 'core',
      muscle: ['abdomen', 'ombro'],
      equipment: ['ab_wheel'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['prancha', 'v_up'],
    },
    {
      id: 'prancha_peso',
      name: 'Prancha com Peso',
      emoji: '🧘',
      type: 'core',
      muscle: ['abdomen', 'lombar'],
      equipment: ['halteres'],
      difficulty: 3,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 1, // segurar
      impacto: 'baixo',
      tempoMedio: 60,
      variations: ['prancha', 'prancha_dinamica'],
    },
    {
      id: 'bicicleta_no_ar',
      name: 'Bicicleta no Ar',
      emoji: '🚴',
      type: 'core',
      muscle: ['abdomen', 'obliquo'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 30,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['abdominal_bicicleta', 'russian_twist'],
    },
    {
      id: 'escalador',
      name: 'Escalador (Mountain Climber)',
      emoji: '⛰️',
      type: 'core',
      muscle: ['abdomen', 'cardio'],
      equipment: ['colchonete'],
      difficulty: 3,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 20,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['mountain_climber', 'prancha_dinamica'],
    },
    {
      id: 'abdominal_completo',
      name: 'Abdominal Completo',
      emoji: '🏋️',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 4,
      baseReps: 25,
      impacto: 'baixo',
      tempoMedio: 40,
      variations: ['abdominal_tradicional', 'abdominal_reverso'],
    },
  ],
};