// arLivre.js - Exercícios ao Ar Livre (35+ exercícios)
import { TIPOS_EXERCICIO, GRUPOS_MUSCULARES, EQUIPAMENTOS, IMPACTO } from './classificacao.js';

export const EXERCICIOS_AR_LIVRE = {
  // ==========================================
  // CAMINHADA (5 variações)
  // ==========================================
  caminhada: [
    {
      id: 'caminhada_leve',
      name: 'Caminhada Leve',
      emoji: '🚶',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 1,
      baseReps: 30, // minutos
      impacto: 'baixo',
      tempoMedio: 1800, // 30min
      variations: ['caminhada_rapida', 'caminhada_subida'],
    },
    {
      id: 'caminhada_rapida',
      name: 'Caminhada Rápida',
      emoji: '🚶‍♂️',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 7,
      baseSets: 1,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 1200,
      variations: ['caminhada_leve', 'caminhada_subida', 'corrida_leve'],
    },
    {
      id: 'caminhada_subida',
      name: 'Caminhada em Subida',
      emoji: '⛰️',
      type: 'cardio',
      muscle: ['quadriceps', 'gluteo', 'panturrilha'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 9,
      baseSets: 1,
      baseReps: 15,
      impacto: 'medio',
      tempoMedio: 900,
      variations: ['caminhada_rapida', 'corrida_subida'],
    },
    {
      id: 'caminhada_piquenique',
      name: 'Caminhada de Piquenique',
      emoji: '🧺',
      type: 'cardio',
      muscle: ['cardio', 'full_body'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 1,
      baseReps: 60,
      impacto: 'baixo',
      tempoMedio: 3600,
      variations: ['caminhada_leve', 'caminhada_rapida'],
    },
    {
      id: 'caminhada_nordica',
      name: 'Caminhada Nórdica',
      emoji: '🎿',
      type: 'cardio',
      muscle: ['cardio', 'ombro', 'costas'],
      equipment: ['bastao'],
      difficulty: 2,
      caloriesPerMin: 8,
      baseSets: 1,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 1200,
      variations: ['caminhada_rapida', 'caminhada_subida'],
    },
  ],

  // ==========================================
  // CORRIDA (7 variações)
  // ==========================================
  corrida: [
    {
      id: 'corrida_leve',
      name: 'Corrida Leve',
      emoji: '🏃',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps', 'posterior'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 10,
      baseSets: 1,
      baseReps: 20,
      impacto: 'medio',
      tempoMedio: 1200,
      variations: ['corrida_moderada', 'caminhada_rapida', 'sprint'],
    },
    {
      id: 'corrida_moderada',
      name: 'Corrida Moderada',
      emoji: '🏃‍♂️',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps', 'posterior'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 13,
      baseSets: 1,
      baseReps: 15,
      impacto: 'medio',
      tempoMedio: 900,
      variations: ['corrida_leve', 'corrida_intensa', 'intervalado'],
    },
    {
      id: 'corrida_intensa',
      name: 'Corrida Intensa',
      emoji: '🔥',
      type: 'cardio',
      muscle: ['cardio', 'full_body'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 16,
      baseSets: 1,
      baseReps: 10,
      impacto: 'alto',
      tempoMedio: 600,
      variations: ['corrida_moderada', 'sprint', 'intervalado'],
    },
    {
      id: 'sprint_curto',
      name: 'Sprint 50m',
      emoji: '💨',
      type: 'explosao',
      muscle: ['full_body', 'posterior', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 20,
      baseSets: 5,
      baseReps: 1,
      impacto: 'alto',
      tempoMedio: 15,
      variations: ['sprint_100m', 'tiros', 'corrida_intensa'],
    },
    {
      id: 'sprint_100m',
      name: 'Sprint 100m',
      emoji: '💨',
      type: 'explosao',
      muscle: ['full_body', 'posterior', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 5,
      caloriesPerMin: 22,
      baseSets: 4,
      baseReps: 1,
      impacto: 'alto',
      tempoMedio: 20,
      variations: ['sprint_curto', 'tiros'],
    },
    {
      id: 'tiros',
      name: 'Tiros (200m)',
      emoji: '🎯',
      type: 'cardio',
      muscle: ['cardio', 'full_body'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 18,
      baseSets: 4,
      baseReps: 1,
      impacto: 'alto',
      tempoMedio: 40,
      variations: ['sprint_curto', 'intervalado'],
    },
    {
      id: 'intervalado',
      name: 'Corrida Intervalada',
      emoji: '⏱️',
      type: 'cardio',
      muscle: ['cardio', 'full_body'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 15,
      baseSets: 1,
      baseReps: 15,
      impacto: 'alto',
      tempoMedio: 900,
      variations: ['corrida_moderada', 'tiros', 'sprint_curto'],
    },
  ],

  // ==========================================
  // ESCADAS (4 variações)
  // ==========================================
  escadas: [
    {
      id: 'subir_escadas',
      name: 'Subir Escadas',
      emoji: '🪜',
      type: 'cardio',
      muscle: ['quadriceps', 'gluteo', 'panturrilha'],
      equipment: ['escada'],
      difficulty: 2,
      caloriesPerMin: 12,
      baseSets: 3,
      baseReps: 5, // lances
      impacto: 'medio',
      tempoMedio: 120,
      variations: ['saltar_degraus', 'escada_lateral'],
    },
    {
      id: 'saltar_degraus',
      name: 'Saltar Degraus',
      emoji: '🦘',
      type: 'explosao',
      muscle: ['quadriceps', 'gluteo', 'panturrilha'],
      equipment: ['escada'],
      difficulty: 4,
      caloriesPerMin: 16,
      baseSets: 3,
      baseReps: 3,
      impacto: 'alto',
      tempoMedio: 60,
      variations: ['subir_escadas', 'agachamento_salto'],
    },
    {
      id: 'escada_lateral',
      name: 'Escada Lateral',
      emoji: '↔️',
      type: 'cardio',
      muscle: ['adutor', 'gluteo', 'quadriceps'],
      equipment: ['escada'],
      difficulty: 2,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 5,
      impacto: 'medio',
      tempoMedio: 90,
      variations: ['subir_escadas', 'afundo_lateral'],
    },
    {
      id: 'escada_corrida',
      name: 'Corrida na Escada',
      emoji: '🏃',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps', 'gluteo'],
      equipment: ['escada'],
      difficulty: 4,
      caloriesPerMin: 15,
      baseSets: 1,
      baseReps: 10, // minutos
      impacto: 'alto',
      tempoMedio: 600,
      variations: ['subir_escadas', 'intervalado'],
    },
  ],

  // ==========================================
  // PARQUE / CALISTENIA (10 variações)
  // ==========================================
  parque: [
    {
      id: 'barra_fixa',
      name: 'Barra Fixa',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['barra'],
      difficulty: 4,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 6,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['barra_australiana', 'barra_pegada_aberta', 'hanging_leg_raise'],
    },
    {
      id: 'barra_australiana',
      name: 'Barra Australiana',
      emoji: '🏋️',
      type: 'forca',
      muscle: ['costas', 'biceps'],
      equipment: ['barra'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['barra_fixa', 'remada_invertida'],
    },
    {
      id: 'barra_pegada_aberta',
      name: 'Barra Fixa Pegada Aberta',
      emoji: '🦅',
      type: 'forca',
      muscle: ['costas', 'ombro'],
      equipment: ['barra'],
      difficulty: 5,
      caloriesPerMin: 11,
      baseSets: 3,
      baseReps: 4,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['barra_fixa', 'puxada_alta'],
    },
    {
      id: 'paralelas',
      name: 'Paralelas (Dips)',
      emoji: '💪',
      type: 'forca',
      muscle: ['triceps', 'peito'],
      equipment: ['barra'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['dips_banco', 'flexao_tradicional'],
    },
    {
      id: 'elevacao_joelhos',
      name: 'Elevação de Joelhos na Barra',
      emoji: '🦵',
      type: 'core',
      muscle: ['abdomen', 'quadriceps'],
      equipment: ['barra'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['hanging_leg_raise', 'abdominal_tradicional'],
    },
    {
      id: 'hanging_leg_raise',
      name: 'Hanging Leg Raise',
      emoji: '🦵',
      type: 'core',
      muscle: ['abdomen', 'lombar'],
      equipment: ['barra'],
      difficulty: 5,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 6,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['elevacao_joelhos', 'v_up'],
    },
    {
      id: 'flexao_barras',
      name: 'Flexão nas Barras',
      emoji: '💪',
      type: 'forca',
      muscle: ['peito', 'triceps'],
      equipment: ['barra'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['flexao_tradicional', 'flexao_declinada'],
    },
    {
      id: 'monkey_bars',
      name: 'Monkey Bars',
      emoji: '🐒',
      type: 'forca',
      muscle: ['costas', 'biceps', 'antebraco'],
      equipment: ['barra'],
      difficulty: 3,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 2,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['barra_fixa', 'dead_hang'],
    },
    {
      id: 'dead_hang',
      name: 'Dead Hang (Pendurado)',
      emoji: '🦥',
      type: 'isometria',
      muscle: ['antebraco', 'costas'],
      equipment: ['barra'],
      difficulty: 2,
      caloriesPerMin: 4,
      baseSets: 2,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 45,
      variations: ['barra_fixa', 'barra_australiana'],
    },
    {
      id: 'salto_horizontal',
      name: 'Salto Horizontal',
      emoji: '🦘',
      type: 'explosao',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 12,
      baseSets: 3,
      baseReps: 8,
      impacto: 'alto',
      tempoMedio: 20,
      variations: ['saltos_consecutivos', 'jump_squat'],
    },
  ],

  // ==========================================
  // EXPLOSÃO AO AR LIVRE (5 variações)
  // ==========================================
  explosao: [
    {
      id: 'saltos_consecutivos',
      name: 'Saltos Consecutivos',
      emoji: '🦘',
      type: 'explosao',
      muscle: ['quadriceps', 'gluteo', 'panturrilha'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 14,
      baseSets: 3,
      baseReps: 10,
      impacto: 'alto',
      tempoMedio: 20,
      variations: ['salto_horizontal', 'jump_squat'],
    },
    {
      id: 'corrida_obstaculos',
      name: 'Corrida com Obstáculos',
      emoji: '🚧',
      type: 'cardio',
      muscle: ['full_body', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 16,
      baseSets: 1,
      baseReps: 10,
      impacto: 'alto',
      tempoMedio: 600,
      variations: ['corrida_intensa', 'intervalado'],
    },
    {
      id: 'fartlek',
      name: 'Fartlek (Jogo de Velocidade)',
      emoji: '🎮',
      type: 'cardio',
      muscle: ['cardio', 'full_body'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 14,
      baseSets: 1,
      baseReps: 20,
      impacto: 'medio',
      tempoMedio: 1200,
      variations: ['intervalado', 'corrida_moderada'],
    },
    {
      id: 'corrida_subida',
      name: 'Corrida em Subida',
      emoji: '⛰️',
      type: 'cardio',
      muscle: ['quadriceps', 'gluteo', 'panturrilha'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 17,
      baseSets: 1,
      baseReps: 10,
      impacto: 'alto',
      tempoMedio: 600,
      variations: ['caminhada_subida', 'corrida_intensa'],
    },
    {
      id: 'shuttle_run',
      name: 'Shuttle Run (Vai-e-Vem)',
      emoji: '🏃',
      type: 'explosao',
      muscle: ['full_body', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 18,
      baseSets: 5,
      baseReps: 1,
      impacto: 'alto',
      tempoMedio: 15,
      variations: ['sprint_curto', 'tiros'],
    },
  ],
};