// casa.js - Exercícios para fazer em casa (80+ exercícios)
import { TIPOS_EXERCICIO, GRUPOS_MUSCULARES, EQUIPAMENTOS, IMPACTO } from './classificacao.js';

export const EXERCICIOS_CASA = {
  // ==========================================
  // EMPURRAR (15 variações)
  // ==========================================
  empurrar: [
    {
      id: 'flexao_tradicional',
      name: 'Flexão Tradicional',
      emoji: '💪',
      type: 'forca',
      muscle: ['peito', 'triceps', 'ombro'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 30, // segundos por série
      variations: ['flexao_inclinada', 'flexao_declinada', 'flexao_diamante', 'flexao_aberta'],
    },
    {
      id: 'flexao_inclinada',
      name: 'Flexão Inclinada',
      emoji: '💪',
      type: 'forca',
      muscle: ['peito_superior', 'ombro_frontal'],
      equipment: ['cadeira', 'parede'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['flexao_tradicional', 'flexao_joelho'],
    },
    {
      id: 'flexao_diamante',
      name: 'Flexão Diamante',
      emoji: '💎',
      type: 'forca',
      muscle: ['triceps', 'peito'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['flexao_tradicional', 'flexao_fechada'],
    },
    {
      id: 'flexao_aberta',
      name: 'Flexão Aberta',
      emoji: '🦅',
      type: 'forca',
      muscle: ['peito', 'ombro'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['flexao_tradicional', 'flexao_arqueiro'],
    },
    {
      id: 'flexao_arqueiro',
      name: 'Flexão Arqueiro',
      emoji: '🏹',
      type: 'forca',
      muscle: ['peito', 'triceps', 'ombro'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 6,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['flexao_tradicional', 'flexao_aberta'],
    },
    {
      id: 'flexao_hindu',
      name: 'Flexão Hindu',
      emoji: '🕉️',
      type: 'forca',
      muscle: ['peito', 'ombro', 'costas'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['flexao_tradicional', 'flexao_inclinada'],
    },
    {
      id: 'flexao_explosiva',
      name: 'Flexão Explosiva',
      emoji: '🔥',
      type: 'explosao',
      muscle: ['peito', 'triceps', 'ombro'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 12,
      baseSets: 3,
      baseReps: 5,
      impacto: 'alto',
      tempoMedio: 25,
      variations: ['flexao_tradicional', 'flexao_palma'],
    },
    {
      id: 'flexao_palma',
      name: 'Flexão com Palma',
      emoji: '👏',
      type: 'explosao',
      muscle: ['peito', 'triceps'],
      equipment: ['nenhum'],
      difficulty: 5,
      caloriesPerMin: 14,
      baseSets: 3,
      baseReps: 4,
      impacto: 'alto',
      tempoMedio: 30,
      variations: ['flexao_explosiva'],
    },
    {
      id: 'flexao_joelho',
      name: 'Flexão Ajoelhada',
      emoji: '🧎',
      type: 'forca',
      muscle: ['peito', 'triceps'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['flexao_tradicional', 'flexao_inclinada'],
    },
    {
      id: 'flexao_parede',
      name: 'Flexão na Parede',
      emoji: '🧱',
      type: 'forca',
      muscle: ['peito', 'triceps'],
      equipment: ['parede'],
      difficulty: 1,
      caloriesPerMin: 3,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['flexao_inclinada'],
    },
    {
      id: 'flexao_declinada',
      name: 'Flexão Declinada',
      emoji: '📐',
      type: 'forca',
      muscle: ['peito_superior', 'ombro'],
      equipment: ['cadeira'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['flexao_tradicional', 'flexao_inclinada'],
    },
    {
      id: 'flexao_pausa',
      name: 'Flexão com Pausa',
      emoji: '⏸️',
      type: 'isometria',
      muscle: ['peito', 'triceps'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['flexao_tradicional'],
    },
    {
      id: 'flexao_fechada',
      name: 'Flexão Fechada',
      emoji: '🤏',
      type: 'forca',
      muscle: ['triceps', 'peito'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 8,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['flexao_diamante', 'flexao_tradicional'],
    },
  ],

  // ==========================================
  // PERNAS (18 variações)
  // ==========================================
  pernas: [
    {
      id: 'agachamento_livre',
      name: 'Agachamento Livre',
      emoji: '🦵',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 15,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['agachamento_sumo', 'agachamento_isometrico', 'agachamento_salto'],
    },
    {
      id: 'agachamento_sumo',
      name: 'Agachamento Sumô',
      emoji: '🤼',
      type: 'forca',
      muscle: ['adutor', 'gluteo', 'quadriceps'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['agachamento_livre', 'agachamento_isometrico'],
    },
    {
      id: 'agachamento_isometrico',
      name: 'Agachamento Isométrico',
      emoji: '🛑',
      type: 'isometria',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 1, // segurar por 30-60s
      impacto: 'baixo',
      tempoMedio: 45,
      variations: ['agachamento_livre', 'cadeira_parede'],
    },
    {
      id: 'agachamento_unilateral',
      name: 'Agachamento Unilateral',
      emoji: '🦵',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo', 'equilibrio'],
      equipment: ['cadeira'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 6,
      impacto: 'baixo',
      tempoMedio: 40,
      variations: ['pistol_squat', 'agachamento_livre'],
    },
    {
      id: 'pistol_squat',
      name: 'Pistol Squat Assistido',
      emoji: '🔫',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo', 'equilibrio'],
      equipment: ['cadeira', 'parede'],
      difficulty: 5,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 4,
      impacto: 'baixo',
      tempoMedio: 45,
      variations: ['agachamento_unilateral'],
    },
    {
      id: 'afundo',
      name: 'Afundo (Avanço)',
      emoji: '🚶',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['afundo_reverso', 'afundo_lateral', 'passada_andando'],
    },
    {
      id: 'afundo_reverso',
      name: 'Afundo Reverso',
      emoji: '🔙',
      type: 'forca',
      muscle: ['gluteo', 'posterior'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['afundo', 'afundo_lateral'],
    },
    {
      id: 'afundo_lateral',
      name: 'Afundo Lateral',
      emoji: '↔️',
      type: 'forca',
      muscle: ['adutor', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['afundo', 'afundo_reverso'],
    },
    {
      id: 'passada_andando',
      name: 'Passada Andando',
      emoji: '🚶‍♂️',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['afundo', 'afundo_reverso'],
    },
    {
      id: 'ponte_gluteo',
      name: 'Ponte de Glúteo',
      emoji: '🍑',
      type: 'forca',
      muscle: ['gluteo', 'posterior'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['ponte_unilateral', 'ponte_elevada'],
    },
    {
      id: 'ponte_unilateral',
      name: 'Ponte Unilateral',
      emoji: '🍑',
      type: 'forca',
      muscle: ['gluteo', 'posterior'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['ponte_gluteo'],
    },
    {
      id: 'panturrilha',
      name: 'Elevação de Panturrilha',
      emoji: '🦶',
      type: 'forca',
      muscle: ['panturrilha'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 4,
      baseReps: 25,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['panturrilha_unilateral', 'panturrilha_degrau'],
    },
    {
      id: 'panturrilha_unilateral',
      name: 'Panturrilha Unilateral',
      emoji: '🦶',
      type: 'forca',
      muscle: ['panturrilha'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['panturrilha', 'panturrilha_degrau'],
    },
    {
      id: 'agachamento_salto',
      name: 'Agachamento com Salto',
      emoji: '🔥',
      type: 'explosao',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 14,
      baseSets: 3,
      baseReps: 8,
      impacto: 'alto',
      tempoMedio: 30,
      variations: ['agachamento_livre', 'jump_squat'],
    },
    {
      id: 'step_up',
      name: 'Step-Up na Cadeira',
      emoji: '🪑',
      type: 'forca',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['cadeira'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 12,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['afundo', 'agachamento_unilateral'],
    },
    {
      id: 'cadeira_parede',
      name: 'Cadeira na Parede',
      emoji: '🧱',
      type: 'isometria',
      muscle: ['quadriceps', 'gluteo'],
      equipment: ['parede'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 2,
      baseReps: 1, // segurar
      impacto: 'baixo',
      tempoMedio: 60,
      variations: ['agachamento_isometrico'],
    },
    {
      id: 'elevacao_quadril',
      name: 'Elevação de Quadril',
      emoji: '🦵',
      type: 'forca',
      muscle: ['gluteo', 'posterior'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['ponte_gluteo', 'ponte_unilateral'],
    },
  ],

  // ==========================================
  // ABDÔMEN (15 variações)
  // ==========================================
  abdomen: [
    {
      id: 'prancha',
      name: 'Prancha Abdominal',
      emoji: '🧘',
      type: 'core',
      muscle: ['abdomen', 'lombar'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 1, // segurar
      impacto: 'baixo',
      tempoMedio: 45,
      variations: ['prancha_lateral', 'prancha_dinamica'],
    },
    {
      id: 'prancha_lateral',
      name: 'Prancha Lateral',
      emoji: '🧘',
      type: 'core',
      muscle: ['obliquo', 'abdomen'],
      equipment: ['colchonete'],
      difficulty: 3,
      caloriesPerMin: 5,
      baseSets: 2,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['prancha', 'prancha_dinamica'],
    },
    {
      id: 'prancha_dinamica',
      name: 'Prancha Dinâmica',
      emoji: '🔄',
      type: 'core',
      muscle: ['abdomen', 'obliquo', 'ombro'],
      equipment: ['colchonete'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['prancha', 'mountain_climber'],
    },
    {
      id: 'mountain_climber',
      name: 'Mountain Climber',
      emoji: '⛰️',
      type: 'core',
      muscle: ['abdomen', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 20,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['prancha_dinamica', 'burpee'],
    },
    {
      id: 'abdominal_tradicional',
      name: 'Abdominal Tradicional',
      emoji: '🏋️',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['abdominal_reverso', 'abdominal_bicicleta'],
    },
    {
      id: 'abdominal_reverso',
      name: 'Abdominal Reverso',
      emoji: '🔄',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['abdominal_tradicional', 'elevacao_pernas'],
    },
    {
      id: 'abdominal_bicicleta',
      name: 'Abdominal Bicicleta',
      emoji: '🚴',
      type: 'core',
      muscle: ['abdomen', 'obliquo'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['abdominal_tradicional', 'russian_twist'],
    },
    {
      id: 'v_up',
      name: 'V-Up',
      emoji: '✅',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['colchonete'],
      difficulty: 4,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['abdominal_tradicional', 'hollow_hold'],
    },
    {
      id: 'hollow_hold',
      name: 'Hollow Hold',
      emoji: '🕳️',
      type: 'isometria',
      muscle: ['abdomen', 'lombar'],
      equipment: ['colchonete'],
      difficulty: 3,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 40,
      variations: ['prancha', 'v_up'],
    },
    {
      id: 'dead_bug',
      name: 'Dead Bug',
      emoji: '🐛',
      type: 'core',
      muscle: ['abdomen', 'lombar'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['bird_dog', 'hollow_hold'],
    },
    {
      id: 'russian_twist',
      name: 'Russian Twist',
      emoji: '🔄',
      type: 'core',
      muscle: ['obliquo', 'abdomen'],
      equipment: ['colchonete'],
      difficulty: 2,
      caloriesPerMin: 6,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['abdominal_bicicleta', 'toque_calcanhar'],
    },
    {
      id: 'bird_dog',
      name: 'Bird Dog',
      emoji: '🐕',
      type: 'equilibrio',
      muscle: ['lombar', 'abdomen', 'gluteo'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['dead_bug', 'superman'],
    },
    {
      id: 'superman',
      name: 'Superman',
      emoji: '🦸',
      type: 'core',
      muscle: ['lombar', 'gluteo'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 15,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['bird_dog', 'natacao_chao'],
    },
    {
      id: 'elevacao_pernas',
      name: 'Elevação de Pernas',
      emoji: '🦵',
      type: 'core',
      muscle: ['abdomen'],
      equipment: ['colchonete'],
      difficulty: 3,
      caloriesPerMin: 7,
      baseSets: 3,
      baseReps: 12,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['abdominal_reverso', 'v_up'],
    },
    {
      id: 'toque_calcanhar',
      name: 'Toque no Calcanhar',
      emoji: '👟',
      type: 'core',
      muscle: ['obliquo'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 4,
      baseSets: 3,
      baseReps: 20,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['russian_twist', 'abdominal_bicicleta'],
    },
  ],

  // ==========================================
  // CARDIO (12 variações)
  // ==========================================
  cardio: [
    {
      id: 'polichinelo',
      name: 'Polichinelo',
      emoji: '⭐',
      type: 'cardio',
      muscle: ['full_body', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 30,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['jumping_jack', 'high_knees'],
    },
    {
      id: 'corrida_parada',
      name: 'Corrida Parada',
      emoji: '🏃',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 1, // minutos
      impacto: 'medio',
      tempoMedio: 60,
      variations: ['high_knees', 'butt_kicks'],
    },
    {
      id: 'high_knees',
      name: 'High Knees',
      emoji: '🦵',
      type: 'cardio',
      muscle: ['cardio', 'quadriceps'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 12,
      baseSets: 3,
      baseReps: 20,
      impacto: 'medio',
      tempoMedio: 25,
      variations: ['corrida_parada', 'butt_kicks'],
    },
    {
      id: 'butt_kicks',
      name: 'Butt Kicks',
      emoji: '🦶',
      type: 'cardio',
      muscle: ['cardio', 'posterior'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 20,
      impacto: 'medio',
      tempoMedio: 25,
      variations: ['corrida_parada', 'high_knees'],
    },
    {
      id: 'burpee',
      name: 'Burpee',
      emoji: '🔥',
      type: 'explosao',
      muscle: ['full_body', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 4,
      caloriesPerMin: 14,
      baseSets: 3,
      baseReps: 8,
      impacto: 'alto',
      tempoMedio: 40,
      variations: ['burpee_sem_salto', 'burpee_completo'],
    },
    {
      id: 'burpee_sem_salto',
      name: 'Burpee sem Salto',
      emoji: '🔥',
      type: 'cardio',
      muscle: ['full_body', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 35,
      variations: ['burpee', 'inchworm'],
    },
    {
      id: 'skater',
      name: 'Skater',
      emoji: '⛸️',
      type: 'cardio',
      muscle: ['adutor', 'gluteo', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 10,
      baseSets: 3,
      baseReps: 15,
      impacto: 'medio',
      tempoMedio: 30,
      variations: ['saltos_laterais', 'afundo_lateral'],
    },
    {
      id: 'jump_squat',
      name: 'Jump Squat',
      emoji: '🦵',
      type: 'explosao',
      muscle: ['quadriceps', 'gluteo', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 13,
      baseSets: 3,
      baseReps: 12,
      impacto: 'alto',
      tempoMedio: 30,
      variations: ['agachamento_salto', 'burpee'],
    },
    {
      id: 'saltos_laterais',
      name: 'Saltos Laterais',
      emoji: '↔️',
      type: 'cardio',
      muscle: ['adutor', 'gluteo', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 2,
      caloriesPerMin: 9,
      baseSets: 3,
      baseReps: 15,
      impacto: 'alto',
      tempoMedio: 25,
      variations: ['skater', 'jump_squat'],
    },
    {
      id: 'bear_crawl',
      name: 'Bear Crawl',
      emoji: '🐻',
      type: 'cardio',
      muscle: ['full_body', 'core'],
      equipment: ['nenhum'],
      difficulty: 3,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 10,
      impacto: 'medio',
      tempoMedio: 40,
      variations: ['inchworm', 'mountain_climber'],
    },
    {
      id: 'inchworm',
      name: 'Inchworm',
      emoji: '🐛',
      type: 'mobilidade',
      muscle: ['full_body', 'posterior'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 5,
      baseSets: 3,
      baseReps: 8,
      impacto: 'baixo',
      tempoMedio: 35,
      variations: ['bear_crawl', 'burpee_sem_salto'],
    },
    {
      id: 'jumping_jack',
      name: 'Jumping Jack',
      emoji: '⭐',
      type: 'cardio',
      muscle: ['full_body', 'cardio'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 8,
      baseSets: 3,
      baseReps: 25,
      impacto: 'medio',
      tempoMedio: 25,
      variations: ['polichinelo', 'high_knees'],
    },
  ],

  // ==========================================
  // MOBILIDADE (10 variações)
  // ==========================================
  mobilidade: [
    {
      id: 'gato_vaca',
      name: 'Gato/Vaca',
      emoji: '🐱',
      type: 'mobilidade',
      muscle: ['lombar', 'abdomen'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['rotacao_toracica', 'cobra'],
    },
    {
      id: 'rotacao_toracica',
      name: 'Rotação Torácica',
      emoji: '🔄',
      type: 'mobilidade',
      muscle: ['costas', 'ombro'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 8,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['gato_vaca', 'alongamento_ombro'],
    },
    {
      id: 'mobilidade_quadril',
      name: 'Mobilidade de Quadril',
      emoji: '🦵',
      type: 'mobilidade',
      muscle: ['gluteo', 'adutor'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 3,
      baseSets: 2,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 25,
      variations: ['alongamento_posterior', 'borboleta'],
    },
    {
      id: 'alongamento_posterior',
      name: 'Alongamento Posterior',
      emoji: '🧘',
      type: 'mobilidade',
      muscle: ['posterior', 'lombar'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 1, // segurar
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['mobilidade_quadril', 'gato_vaca'],
    },
    {
      id: 'alongamento_ombro',
      name: 'Alongamento de Ombro',
      emoji: '💪',
      type: 'mobilidade',
      muscle: ['ombro', 'peito'],
      equipment: ['nenhum'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['rotacao_toracica', 'alongamento_peitoral'],
    },
    {
      id: 'alongamento_peitoral',
      name: 'Alongamento Peitoral',
      emoji: '🦾',
      type: 'mobilidade',
      muscle: ['peito', 'ombro'],
      equipment: ['parede'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['alongamento_ombro', 'rotacao_toracica'],
    },
    {
      id: 'mobilidade_tornozelo',
      name: 'Mobilidade de Tornozelo',
      emoji: '🦶',
      type: 'mobilidade',
      muscle: ['panturrilha', 'tornozelo'],
      equipment: ['parede'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 10,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['panturrilha', 'alongamento_posterior'],
    },
    {
      id: 'cobra',
      name: 'Cobra (Yoga)',
      emoji: '🐍',
      type: 'mobilidade',
      muscle: ['abdomen', 'peito'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 8,
      impacto: 'baixo',
      tempoMedio: 20,
      variations: ['gato_vaca', 'superman'],
    },
    {
      id: 'child_pose',
      name: 'Child Pose (Yoga)',
      emoji: '🧘',
      type: 'mobilidade',
      muscle: ['lombar', 'ombro'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 1,
      baseSets: 2,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 60,
      variations: ['gato_vaca', 'alongamento_posterior'],
    },
    {
      id: 'borboleta',
      name: 'Alongamento Borboleta',
      emoji: '🦋',
      type: 'mobilidade',
      muscle: ['adutor', 'quadril'],
      equipment: ['colchonete'],
      difficulty: 1,
      caloriesPerMin: 2,
      baseSets: 2,
      baseReps: 1,
      impacto: 'baixo',
      tempoMedio: 30,
      variations: ['mobilidade_quadril', 'alongamento_posterior'],
    },
  ],
};